name:                ChaosTheoryGraphics
version:             0.1.0.0
github:              "mqz05/Chaos-Theory-Graphics-Lorenz-System.git"
license:             BSD-3-Clause
author:              "Muqi Zhang"
maintainer:          "s2473175@ed.ac.uk"
copyright:           "2023 Muqi Zhang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mqz05/Chaos-Theory-Graphics-Lorenz-System/blob/main/ChaosTheoryGraphics/README.md>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-lib
- gloss

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ChaosTheoryGraphics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ChaosTheoryGraphics

tests:
  ChaosTheoryGraphics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ChaosTheoryGraphics
